import { ArrowLeft, Edit, Plus, Trash2 } from "lucide-react";
import React, { useState, useEffect } from "react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { addService, fetchAllCategories } from "../../../../services/firestore";
import { useToast } from "../../../../context/ToastContext";
import { ref, uploadBytes, getDownloadURL } from "firebase/storage";
import { storage } from "../../../../config/firebase";

interface Service {
  id: number;
  image: string;
  title: string;
  description: string;
  unit: string;
  status: "active" | "inactive";
}

interface ServiceOption {
  onyxProductId?: string;
  title: { ar: string; en: string };
  desc: { ar: string; en: string };
  companyPrice: number;
  price: number;
  subCategory?: string; // For form input
  mainCategory?: string; // For form input
  description?: string; // For form input (will be mapped to desc)
}

interface OutletContext {
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  setDynamicTitle: (title: string) => void;
}

export const AddService = (): JSX.Element => {
  const navigate = useNavigate();
  const { setDynamicTitle } = useOutletContext<OutletContext>();
  const { addToast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [editedService, setEditedService] = useState<Service>({
    id: 0, // Will be generated by backend
    image: "",
    title: "",
    description: "",
    unit: "لتر",
    status: "active",
  });
  const [serviceOptions, setServiceOptions] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<any>(null);
  const [serviceOption, setServiceOption] = useState({
    subCategory: "",
    mainCategory: "",
    companyPrice: 0,
    price: 0,
    description: "",
  });

  // Update dynamic title on component mount
  React.useEffect(() => {
    setDynamicTitle("خدمات التطبيق / إضافة خدمة جديدة");
  }, [setDynamicTitle]);

  // Fetch categories on component mount
  useEffect(() => {
    const loadCategories = async () => {
      try {
        const categoriesData = await fetchAllCategories();
        setCategories(categoriesData);
      } catch (error) {
        console.error("Error loading categories:", error);
      }
    };
    loadCategories();
  }, []);

  const handleInputChange = (field: keyof Service, value: string) => {
    setEditedService((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleOptionChange = (field: string, value: string | number) => {
    setServiceOption((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleSubmit = async () => {
    if (!editedService.title || !editedService.description) {
      addToast({
        message: "يرجى ملء جميع الحقول المطلوبة",
        type: "error",
      });
      return;
    }

    setIsSubmitting(true);
    try {
      // Upload image to Firebase Storage if it's a base64 data URL
      let imageUrl = editedService.image || "";

      if (editedService.image && editedService.image.startsWith("data:image")) {
        try {
          addToast({
            message: "جاري رفع الصورة...",
            type: "info",
          });

          // Convert base64 to blob
          const response = await fetch(editedService.image);
          const blob = await response.blob();

          // Upload to Firebase Storage
          const timestamp = Date.now();
          const fileName = `services/${timestamp}_${Math.random()
            .toString(36)
            .substring(7)}.png`;
          const storageRef = ref(storage, fileName);

          await uploadBytes(storageRef, blob);
          imageUrl = await getDownloadURL(storageRef);

          console.log("Image uploaded successfully:", imageUrl);
        } catch (uploadError) {
          console.error("Error uploading image:", uploadError);
          addToast({
            message: "فشل في رفع الصورة. سيتم حفظ الخدمة بدون صورة",
            type: "warning",
          });
        }
      }

      // Prepare service data for Firestore
      // Handle multilingual fields - convert strings to {ar: "...", en: "..."} format
      const serviceData: any = {
        // Handle title as multilingual if needed
        title:
          typeof editedService.title === "object"
            ? editedService.title
            : { ar: editedService.title, en: editedService.title },

        // Handle description as multilingual (use 'desc' to match Firestore)
        desc:
          typeof editedService.description === "object"
            ? editedService.description
            : { ar: editedService.description, en: editedService.description },

        // Handle unit as multilingual
        unit:
          typeof editedService.unit === "object"
            ? editedService.unit
            : { ar: editedService.unit, en: editedService.unit },

        // Image URL (not base64)
        image: imageUrl,

        // Status
        status: editedService.status || "active",
        isActive: editedService.status === "active",

        // Service ID (if provided)
        ...(editedService.id && { serviceId: String(editedService.id) }),

        // Options (خيارات) - only send if there are options
        ...(serviceOptions.length > 0 && {
          options: serviceOptions,
        }),
      };

      console.log("Creating service with data:", serviceData);

      await addService(serviceData);

      addToast({
        message: "تم إضافة الخدمة بنجاح!",
        type: "success",
      });

      navigate("/application-services");
    } catch (error) {
      console.error("Error adding service:", error);
      addToast({
        message: "فشل في إضافة الخدمة. يرجى المحاولة مرة أخرى",
        type: "error",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleAddOption = () => {
    if (serviceOption.subCategory && serviceOption.price && selectedCategory) {
      // Convert form data to Firestore structure
      const firestoreOption = {
        onyxProductId: selectedCategory.onyxProductId || `P${Date.now()}`,
        title: {
          ar: serviceOption.subCategory || "",
          en: serviceOption.subCategory || "",
        },
        desc: {
          ar: serviceOption.description || " ",
          en: serviceOption.description || " ",
        },
        companyPrice: Number(serviceOption.companyPrice) || 0,
        price: Number(serviceOption.price) || 0,
        id: null,
        // Include full category data
        category: {
          ...selectedCategory,
          // Ensure createdDate is a serverTimestamp if missing
          ...(selectedCategory.createdDate || {}),
        },
      };

      setServiceOptions([...serviceOptions, firestoreOption]);

      // Reset option form
      setServiceOption({
        subCategory: "",
        mainCategory: "",
        companyPrice: 0,
        price: 0,
        description: "",
      });
      setSelectedCategory(null);

      addToast({
        message: "تم إضافة الخيار بنجاح",
        type: "success",
      });
    } else {
      addToast({
        message: "يرجى ملء جميع الحقول المطلوبة للخيار (الفئة والسعر والعنوان)",
        type: "error",
      });
    }
  };

  const handleDeleteOption = (index: number) => {
    if (window.confirm("هل أنت متأكد من حذف هذا الخيار؟")) {
      setServiceOptions(serviceOptions.filter((_, i) => i !== index));
      addToast({
        message: "تم حذف الخيار بنجاح",
        type: "success",
      });
    }
  };

  // Helper function to get value or dash
  const getValueOrDash = (value: any) => {
    if (value === null || value === undefined || value === "") {
      return "-";
    }
    return String(value);
  };

  // Extract service information
  const serviceInfo = {
    id: getValueOrDash(editedService.id),
    title: getValueOrDash(editedService.title),
    description: getValueOrDash(editedService.description),
    unit: getValueOrDash(editedService.unit),
    status: editedService.status,
    image: editedService.image,
  };

  // Define all fields to display in 3-column layout
  const fields: FieldType[] = [
    {
      label: "صورة الخدمة",
      value: serviceInfo.image,
      editable: true,
      field: "image" as keyof Service,
      type: "image" as const,
    },
    {
      label: "الرقم التعريفي",
      value: serviceInfo.id,
      editable: true,
      field: "id" as keyof Service,
    },
    {
      label: "الوحدة",
      value: serviceInfo.unit,
      editable: true,
      field: "unit" as keyof Service,
    },
  ];

  // Define field type
  interface FieldType {
    label: string;
    value: string;
    editable: boolean;
    field: keyof Service;
    type?: "image";
  }

  // Helper function to render field
  const renderField = (field: FieldType) => (
    <div className="flex flex-col gap-2 flex-1">
      <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
        {field.label}
      </label>
      {field.type === "image" ? (
        <div className="relative">
          <input
            type="file"
            accept="image/*"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) {
                const reader = new FileReader();
                reader.onload = (event) => {
                  handleInputChange(
                    field.field,
                    event.target?.result as string
                  );
                };
                reader.readAsDataURL(file);
              }
            }}
            className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-[#5A66C1] file:text-white hover:file:bg-[#4A56B1]"
            dir="rtl"
          />
          {editedService[field.field] && (
            <div className="mt-2">
              <img
                src={String(editedService[field.field])}
                alt="صورة الخدمة"
                className="w-32 h-32 object-cover rounded-lg border-2 border-gray-300"
                onError={(e) => {
                  e.currentTarget.style.display = "none";
                }}
              />
            </div>
          )}
        </div>
      ) : field.field === "unit" ? (
        <select
          value={editedService[field.field]}
          onChange={(e) => handleInputChange(field.field, e.target.value)}
          className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
          dir="rtl"
        >
          <option value="لتر">لتر</option>
          <option value="حبة">حبة</option>
          <option value="كيلو">كيلو</option>
          <option value="متر">متر</option>
        </select>
      ) : (
        <input
          type="text"
          value={editedService[field.field]}
          onChange={(e) => handleInputChange(field.field, e.target.value)}
          className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
          dir="rtl"
          disabled={!field.editable}
          placeholder={`أدخل ${field.label.toLowerCase()}`}
        />
      )}
    </div>
  );

  // Helper function to render rows of 3 columns
  const renderFieldRows = () => {
    const rows: React.ReactNode[] = [];
    for (let i = 0; i < fields.length; i += 3) {
      const rowFields = fields.slice(i, i + 3);
      rows.push(
        <div
          key={i}
          className="flex items-start gap-5 relative self-stretch w-full flex-[0_0_auto]"
        >
          {rowFields.map((field, index) => (
            <React.Fragment key={index}>{renderField(field)}</React.Fragment>
          ))}
          {/* Fill remaining columns if less than 3 */}
          {rowFields.length < 3 &&
            Array.from({ length: 3 - rowFields.length }).map((_, index) => (
              <div key={`empty-${index}`} className="flex-1" />
            ))}
        </div>
      );
    }
    return rows;
  };

  return (
    <div>
      <main
        className="flex flex-col items-start gap-[var(--corner-radius-extra-large)] pt-[var(--corner-radius-large)] pr-[var(--corner-radius-large)] pb-[var(--corner-radius-large)] pl-[var(--corner-radius-large)] relative bg-color-mode-surface-bg-screen rounded-[var(--corner-radius-large)] border-[0.3px] border-solid border-color-mode-text-icons-t-placeholder"
        data-model-id="service-info"
      >
        <header className="flex flex-col items-end gap-[var(--corner-radius-extra-large)] relative self-stretch w-full flex-[0_0_auto]">
          <nav className="flex items-center justify-between relative self-stretch w-full flex-[0_0_auto]">
            <button
              onClick={() => navigate(-1)}
              className="inline-flex h-10 items-center gap-[var(--corner-radius-medium)] relative flex-[0_0_auto]"
              aria-label="العودة"
            >
              <div className="flex flex-col w-10 items-center justify-center gap-2.5 pt-[var(--corner-radius-small)] pb-[var(--corner-radius-small)] px-2.5 relative self-stretch bg-color-mode-surface-bg-icon-gray rounded-[var(--corner-radius-small)]">
                <ArrowLeft className="w-4 h-4 text-gray-600" />
              </div>
            </button>

            <div className="flex items-center justify-end gap-1.5 relative">
              <h1 className="w-[145px] h-5 mt-[-1.00px] font-bold text-[var(--form-section-title-color)] text-[length:var(--subtitle-subtitle-2-font-size)] tracking-[var(--subtitle-subtitle-2-letter-spacing)] leading-[var(--subtitle-subtitle-2-line-height)] whitespace-nowrap relative [direction:rtl] [font-style:var(--subtitle-subtitle-2-font-style)]">
                إضافة خدمة جديدة
              </h1>
              <Plus className="w-5 h-5 text-gray-500" />
            </div>
          </nav>
        </header>

        <section className="flex flex-col items-start gap-5 relative self-stretch w-full flex-[0_0_auto]">
          <div className="flex flex-col items-end gap-2.5 relative self-stretch w-full flex-[0_0_auto]">
            <form className="flex flex-col items-start gap-5 relative self-stretch w-full flex-[0_0_auto]">
              {/* Service Name Input - Full Width */}
              <div className="flex flex-col gap-2 relative self-stretch w-full flex-[0_0_auto]">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  اسم الخدمة
                </label>
                <input
                  type="text"
                  value={editedService.title}
                  onChange={(e) => handleInputChange("title", e.target.value)}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  dir="rtl"
                  placeholder="أدخل اسم الخدمة"
                />
              </div>

              {/* Service Description Input - Full Width */}
              <div className="flex flex-col gap-2 relative self-stretch w-full flex-[0_0_auto]">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  وصف الخدمة
                </label>
                <textarea
                  value={editedService.description}
                  onChange={(e) =>
                    handleInputChange("description", e.target.value)
                  }
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  rows={3}
                  dir="rtl"
                  placeholder="أدخل وصف الخدمة"
                />
              </div>

              {/* Dynamic fields in 3-column layout */}
              {renderFieldRows()}

              {/* Submit Button */}
              <div className="flex justify-end mt-6">
                <button
                  onClick={handleSubmit}
                  disabled={isSubmitting}
                  className="px-[10px] py-3 bg-[#5A66C1] text-white rounded-[8px] font-medium hover:bg-[#4A56B1] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isSubmitting ? "جاري الإضافة..." : "إضافة الخدمة"}
                </button>
              </div>
            </form>
          </div>
        </section>
      </main>

      {/* Second Main Section */}
      <main
        className="flex flex-col items-start gap-[var(--corner-radius-extra-large)] pt-[var(--corner-radius-large)] pr-[var(--corner-radius-large)] pb-[var(--corner-radius-large)] pl-[var(--corner-radius-large)] relative bg-color-mode-surface-bg-screen rounded-[var(--corner-radius-large)] border-[0.3px] border-solid border-color-mode-text-icons-t-placeholder mt-6"
        data-model-id="service-additional-info"
      >
        <header className="flex flex-col items-end gap-[var(--corner-radius-extra-large)] relative self-stretch w-full flex-[0_0_auto]">
          <nav className="flex items-center justify-between relative self-stretch w-full flex-[0_0_auto]">
            <div className="flex items-center">
              <button
                onClick={handleAddOption}
                className="px-[10px] py-[8px] bg-[#F5F6F766] text-[#5B738B] rounded-[8px] font-normal text-[14px] hover:bg-[#E8E9EA] transition-colors flex items-center gap-2"
                style={{ border: "0.8px solid #A9B4BE" }}
              >
                إضافة خيار جديد <Plus className="w-4 h-4" />
              </button>
            </div>

            <div className="flex items-center justify-end gap-1.5 relative">
              <h1 className="w-[145px] h-5 mt-[-1.00px] font-bold text-[var(--form-section-title-color)] text-[length:var(--subtitle-subtitle-2-font-size)] tracking-[var(--subtitle-subtitle-2-letter-spacing)] leading-[var(--subtitle-subtitle-2-line-height)] whitespace-nowrap relative [direction:rtl] [font-style:var(--subtitle-subtitle-2-font-style)]">
                خيارات
              </h1>
              <Edit className="w-5 h-5 text-gray-500" />
            </div>
          </nav>
        </header>

        <section className="flex flex-col items-start gap-5 relative self-stretch w-full flex-[0_0_auto]">
          {/* Option Form */}
          <div className="flex flex-col gap-4 w-full border border-gray-200 rounded-lg p-4 bg-gray-50">
            <h3 className="text-sm font-semibold text-gray-700">
              إضافة خيار جديد
            </h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col gap-2">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  الفئة الرئيسية
                </label>
                <select
                  value={selectedCategory?.id || ""}
                  onChange={(e) => {
                    const categoryId = e.target.value;
                    if (!categoryId) {
                      setSelectedCategory(null);
                      return;
                    }
                    const category = categories.find(
                      (cat) => cat.id === categoryId
                    );
                    setSelectedCategory(category || null);
                  }}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  dir="rtl"
                >
                  <option value="">اختر الفئة</option>
                  {categories
                    .filter((category) => category.id) // Only show categories with valid IDs
                    .map((category) => {
                      const categoryName =
                        typeof category.name === "object"
                          ? category.name.ar || category.name.en
                          : category.name || category.label || "بدون اسم";
                      return (
                        <option key={category.id} value={category.id}>
                          {categoryName}
                        </option>
                      );
                    })}
                </select>
              </div>
              <div className="flex flex-col gap-2">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  الفئة الفرعية
                </label>
                <input
                  type="text"
                  value={serviceOption.subCategory}
                  onChange={(e) =>
                    handleOptionChange("subCategory", e.target.value)
                  }
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  dir="rtl"
                  placeholder="مثل: بنزين 91"
                />
              </div>
              <div className="flex flex-col gap-2">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  السعر
                </label>
                <input
                  type="number"
                  value={serviceOption.price}
                  onChange={(e) =>
                    handleOptionChange("price", parseFloat(e.target.value) || 0)
                  }
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  dir="rtl"
                  placeholder="0"
                />
              </div>
              <div className="flex flex-col gap-2">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  سعر الشركة
                </label>
                <input
                  type="number"
                  value={serviceOption.companyPrice}
                  onChange={(e) =>
                    handleOptionChange(
                      "companyPrice",
                      parseFloat(e.target.value) || 0
                    )
                  }
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  dir="rtl"
                  placeholder="0"
                />
              </div>
              <div className="flex flex-col gap-2 col-span-2">
                <label className="text-sm font-normal text-[var(--form-readonly-label-color)] [direction:rtl] text-right">
                  الوصف
                </label>
                <textarea
                  value={serviceOption.description}
                  onChange={(e) =>
                    handleOptionChange("description", e.target.value)
                  }
                  className="px-3 py-2 border border-gray-300 rounded-lg text-[var(--form-readonly-input-text-color)] [direction:rtl] text-right font-normal focus:outline-none focus:ring-2 focus:ring-[#5A66C1] focus:border-transparent"
                  rows={2}
                  dir="rtl"
                  placeholder="وصف الخيار"
                />
              </div>
            </div>
          </div>

          {/* Options List */}
          {serviceOptions.length > 0 && (
            <div className="flex flex-col gap-3 w-full">
              <h3 className="text-sm font-semibold text-gray-700">
                الخيارات المضافة ({serviceOptions.length})
              </h3>
              {serviceOptions.map((option, index) => (
                <div
                  key={index}
                  className="flex items-center justify-between p-4 border border-gray-200 rounded-lg bg-white"
                >
                  <div className="flex flex-col gap-1 [direction:rtl] text-right">
                    <p className="font-medium text-gray-800">
                      {typeof option.title === "object"
                        ? option.title.ar
                        : option.subCategory || "بدون عنوان"}
                    </p>
                    {option.category && (
                      <p className="text-xs text-gray-500">
                        الفئة:{" "}
                        {typeof option.category.name === "object"
                          ? option.category.name.ar || option.category.name.en
                          : option.category.name ||
                            option.category.label ||
                            "-"}
                      </p>
                    )}
                    <p className="text-sm text-gray-600">
                      السعر: {option.price} | سعر الشركة: {option.companyPrice}
                    </p>
                    {option.desc &&
                      typeof option.desc === "object" &&
                      option.desc.ar && (
                        <p className="text-xs text-gray-500">
                          {option.desc.ar}
                        </p>
                      )}
                    {option.description &&
                      typeof option.description === "string" && (
                        <p className="text-xs text-gray-500">
                          {option.description}
                        </p>
                      )}
                  </div>
                  <button
                    onClick={() => handleDeleteOption(index)}
                    className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                  >
                    <Trash2 className="w-5 h-5" />
                  </button>
                </div>
              ))}
            </div>
          )}
        </section>
      </main>
    </div>
  );
};

export default AddService;
